import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Navigation from "./_components/_home/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Ebugi-Time App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Navigation />
        <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
          <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
